baseURL = "https://mckjhd.github.io/pages/"
languageCode = "en"
title = "Curated links collection"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Disqus Username
disqusShortname = "jamhed"

# Google Analytics UA number
googleAnalytics = "UA-137877117-1"

# Initial site menu, you can extend menu with content.

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Roman Galeev"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "Curated links collection"
  description = "Curated pages collection"
  paginate = 20

  # Choose your social networks
  email = "roman_galeev@mckinsey.com"
  github = "mckjhd"
  # twitter = "twitter_username"
  linkedin = "jamhed"
  # facebook = "facebook_username"
  # google = "googlplus_id_number"
  # instagram = "instagram_username"
  # youtube = "youtube_username"
  # vimeo = "vimeo_username"
  # medium = "medium_username"
  # quora = "quora_username"
  # pinterest = "pinterest_username"
  # dribbble = "dribbble_username"
  # behance = "behance_username"
  # jsfiddle = "jsfiddle_username"
  # codepen = "codepen_username"

  # Overrid theme styles in this file
  # customStyle = "styles/custom.scss"
